import '@/styles/global.css'
import ModalProvider from '@/providers/ModalProvider'
import QueryProvider from '@/providers/QueryClientProvider'



export const metadata = {
  title: 'Together',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ModalProvider />
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  )
}
